##### Copyright 2019 The TensorFlow Authors.

Licensed under the Apache License, Version 2.0 (the "License");

In [1]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Load a pandas.DataFrame

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://www.tensorflow.org/tutorials/load_data/pandas_dataframe"><img src="https://www.tensorflow.org/images/tf_logo_32px.png" />View on TensorFlow.org</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/load_data/pandas_dataframe.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/tensorflow/docs/blob/master/site/en/tutorials/load_data/pandas_dataframe.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/load_data/pandas_dataframe.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png" />Download notebook</a>
  </td>
</table>

This tutorial provides an example of how to load pandas dataframes into a `tf.data.Dataset`.

This tutorials uses a small [dataset](https://archive.ics.uci.edu/ml/datasets/heart+Disease) provided by the Cleveland Clinic Foundation for Heart Disease. There are several hundred rows in the CSV. Each row describes a patient, and each column describes an attribute. We will use this information to predict whether a patient has heart disease, which in this dataset is a binary classification task.

## Read data using pandas

In [2]:
import pandas as pd
import tensorflow as tf

Download the csv file containing the heart dataset.

In [3]:
csv_file = tf.keras.utils.get_file('heart.csv', 'https://storage.googleapis.com/download.tensorflow.org/data/heart.csv')

 8192/13273 [=================>............] - ETA: 0s

16384/13273 [=====================================] - 0s 0us/step


Read the csv file using pandas.

In [4]:
df = pd.read_csv(csv_file)

In [5]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca        thal  target  
0   0       fixed       0  
1   3      normal       1  
2   2  reversible       0  
3   0      normal       0  
4   0      normal       0

In [6]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal         object
target        int64
dtype: object

Convert `thal` column which is an `object` in the dataframe to a discrete numerical value.

In [7]:
df['thal'] = pd.Categorical(df['thal'])
df['thal'] = df.thal.cat.codes

In [8]:
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   1       145   233    1        2      150      0      2.3      3   
1   67    1   4       160   286    0        2      108      1      1.5      2   
2   67    1   4       120   229    0        2      129      1      2.6      2   
3   37    1   3       130   250    0        0      187      0      3.5      3   
4   41    0   2       130   204    0        2      172      0      1.4      1   

   ca  thal  target  
0   0     2       0  
1   3     3       1  
2   2     4       0  
3   0     3       0  
4   0     3       0

## Load data using `tf.data.Dataset`

Use `tf.data.Dataset.from_tensor_slices` to read the values from a pandas dataframe. 

One of the advantages of using `tf.data.Dataset` is it allows you to write simple, highly efficient data pipelines. Read the [loading data guide](https://www.tensorflow.org/guide/data) to find out more.

In [9]:
target = df.pop('target')

In [10]:
dataset = tf.data.Dataset.from_tensor_slices((df.values, target.values))

In [11]:
for feat, targ in dataset.take(5):
  print ('Features: {}, Target: {}'.format(feat, targ))

Features: [ 63.    1.    1.  145.  233.    1.    2.  150.    0.    2.3   3.    0.
   2. ], Target: 0
Features: [ 67.    1.    4.  160.  286.    0.    2.  108.    1.    1.5   2.    3.
   3. ], Target: 1
Features: [ 67.    1.    4.  120.  229.    0.    2.  129.    1.    2.6   2.    2.
   4. ], Target: 0
Features: [ 37.    1.    3.  130.  250.    0.    0.  187.    0.    3.5   3.    0.
   3. ], Target: 0
Features: [ 41.    0.    2.  130.  204.    0.    2.  172.    0.    1.4   1.    0.
   3. ], Target: 0


Since a `pd.Series` implements the `__array__` protocol it can be used transparently nearly anywhere you would use a `np.array` or a `tf.Tensor`.

In [12]:
tf.constant(df['thal'])

<tf.Tensor: shape=(303,), dtype=int8, numpy=
array([2, 3, 4, 3, 3, 3, 3, 3, 4, 4, 2, 3, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3,
       3, 4, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 4, 2, 4, 3, 4, 3, 4, 4,
       2, 3, 3, 4, 3, 3, 4, 3, 3, 3, 4, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 4,
       4, 2, 3, 3, 4, 3, 4, 3, 3, 4, 4, 3, 3, 4, 4, 3, 3, 3, 3, 4, 4, 4,
       3, 3, 4, 3, 4, 4, 3, 4, 3, 3, 3, 4, 3, 4, 4, 3, 3, 4, 4, 4, 4, 4,
       3, 3, 3, 3, 4, 3, 4, 3, 4, 4, 3, 3, 2, 4, 4, 2, 3, 3, 4, 4, 3, 4,
       3, 3, 4, 2, 4, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4,
       4, 3, 3, 3, 4, 3, 4, 3, 4, 3, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 4, 4, 3, 3, 3, 3, 3, 3, 3, 3, 4, 3, 4, 3, 2,
       4, 4, 3, 3, 3, 3, 3, 3, 4, 3, 3, 3, 3, 3, 2, 2, 4, 3, 4, 2, 4, 3,
       3, 4, 3, 3, 3, 3, 4, 3, 4, 3, 4, 2, 2, 4, 3, 4, 3, 2, 4, 3, 3, 2,
       4, 4, 4, 4, 3, 0, 3, 3, 3, 3, 1, 4, 3, 3, 3, 4, 3, 4, 3, 3, 3, 4,
       3, 3, 4, 4, 4, 4, 3, 3, 4, 3, 4, 3, 4, 4, 3, 4, 4, 3, 4, 4, 3, 3,
      

Shuffle and batch the dataset.

In [13]:
train_dataset = dataset.shuffle(len(df)).batch(1)

## Create and train a model

In [14]:
def get_compiled_model():
  model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(1)
  ])

  model.compile(optimizer='adam',
                loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                metrics=['accuracy'])
  return model

In [15]:
model = get_compiled_model()
model.fit(train_dataset, epochs=15)

Epoch 1/15

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



  1/303 [..............................] - ETA: 0s - loss: 4.7758e-35 - accuracy: 1.0000

 26/303 [=>............................] - ETA: 0s - loss: 40.3426 - accuracy: 0.3462   

 52/303 [====>.........................] - ETA: 0s - loss: 24.6790 - accuracy: 0.4038

 78/303 [======>.......................] - ETA: 0s - loss: 16.9939 - accuracy: 0.4744

104/303 [=========>....................] - ETA: 0s - loss: 12.8992 - accuracy: 0.5769

129/303 [===========>..................] - ETA: 0s - loss: 11.0281 - accuracy: 0.5581

153/303 [==============>...............] - ETA: 0s - loss: 9.6328 - accuracy: 0.5621 

178/303 [================>.............] - ETA: 0s - loss: 8.4010 - accuracy: 0.5843

204/303 [===================>..........] - ETA: 0s - loss: 7.4940 - accuracy: 0.5882

230/303 [=====================>........] - ETA: 0s - loss: 6.8592 - accuracy: 0.5783

257/303 [========================>.....] - ETA: 0s - loss: 6.2947 - accuracy: 0.5837

284/303 [===========================>..] - ETA: 0s - loss: 5.8293 - accuracy: 0.5880

303/303 [==============================] - 1s 2ms/step - loss: 5.5209 - accuracy: 0.5974


Epoch 2/15
  1/303 [..............................] - ETA: 0s - loss: 0.0045 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 1.6983 - accuracy: 0.5926

 53/303 [====>.........................] - ETA: 0s - loss: 1.3266 - accuracy: 0.6415

 79/303 [======>.......................] - ETA: 0s - loss: 1.3825 - accuracy: 0.6203

105/303 [=========>....................] - ETA: 0s - loss: 1.4004 - accuracy: 0.5810

131/303 [===========>..................] - ETA: 0s - loss: 1.2894 - accuracy: 0.5878

157/303 [==============>...............] - ETA: 0s - loss: 1.1740 - accuracy: 0.6369

183/303 [=================>............] - ETA: 0s - loss: 1.1567 - accuracy: 0.6503

208/303 [===================>..........] - ETA: 0s - loss: 1.1188 - accuracy: 0.6683

234/303 [======================>.......] - ETA: 0s - loss: 1.1251 - accuracy: 0.6538

259/303 [========================>.....] - ETA: 0s - loss: 1.1184 - accuracy: 0.6448

284/303 [===========================>..] - ETA: 0s - loss: 1.0685 - accuracy: 0.6549

303/303 [==============================] - 1s 2ms/step - loss: 1.0674 - accuracy: 0.6502


Epoch 3/15
  1/303 [..............................] - ETA: 0s - loss: 1.7971 - accuracy: 0.0000e+00

 27/303 [=>............................] - ETA: 0s - loss: 0.8405 - accuracy: 0.5185    

 52/303 [====>.........................] - ETA: 0s - loss: 0.7483 - accuracy: 0.6154

 77/303 [======>.......................] - ETA: 0s - loss: 0.7529 - accuracy: 0.6234

102/303 [=========>....................] - ETA: 0s - loss: 0.7407 - accuracy: 0.6275

128/303 [===========>..................] - ETA: 0s - loss: 0.6972 - accuracy: 0.6641

153/303 [==============>...............] - ETA: 0s - loss: 0.8147 - accuracy: 0.6275

179/303 [================>.............] - ETA: 0s - loss: 0.8116 - accuracy: 0.6480

205/303 [===================>..........] - ETA: 0s - loss: 0.7943 - accuracy: 0.6537

231/303 [=====================>........] - ETA: 0s - loss: 0.8180 - accuracy: 0.6494

257/303 [========================>.....] - ETA: 0s - loss: 0.7892 - accuracy: 0.6654

283/303 [===========================>..] - ETA: 0s - loss: 0.7540 - accuracy: 0.6784

303/303 [==============================] - 1s 2ms/step - loss: 0.7267 - accuracy: 0.6931


Epoch 4/15
  1/303 [..............................] - ETA: 0s - loss: 0.0925 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 0.7208 - accuracy: 0.8148

 53/303 [====>.........................] - ETA: 0s - loss: 0.6929 - accuracy: 0.7547

 79/303 [======>.......................] - ETA: 0s - loss: 0.7261 - accuracy: 0.7342

103/303 [=========>....................] - ETA: 0s - loss: 0.6937 - accuracy: 0.7184

130/303 [===========>..................] - ETA: 0s - loss: 0.6621 - accuracy: 0.7154

155/303 [==============>...............] - ETA: 0s - loss: 0.6312 - accuracy: 0.7290

180/303 [================>.............] - ETA: 0s - loss: 0.6257 - accuracy: 0.7389

206/303 [===================>..........] - ETA: 0s - loss: 0.6375 - accuracy: 0.7330

232/303 [=====================>........] - ETA: 0s - loss: 0.6598 - accuracy: 0.7328

258/303 [========================>.....] - ETA: 0s - loss: 0.6851 - accuracy: 0.7326

283/303 [===========================>..] - ETA: 0s - loss: 0.6853 - accuracy: 0.7244

303/303 [==============================] - 1s 2ms/step - loss: 0.6754 - accuracy: 0.7261


Epoch 5/15


  1/303 [..............................] - ETA: 0s - loss: 1.9544 - accuracy: 0.0000e+00

 28/303 [=>............................] - ETA: 0s - loss: 0.9514 - accuracy: 0.6786    

 55/303 [====>.........................] - ETA: 0s - loss: 0.7758 - accuracy: 0.7455

 81/303 [=======>......................] - ETA: 0s - loss: 0.7343 - accuracy: 0.7531

107/303 [=========>....................] - ETA: 0s - loss: 0.6928 - accuracy: 0.7383

132/303 [============>.................] - ETA: 0s - loss: 0.6602 - accuracy: 0.7500

159/303 [==============>...............] - ETA: 0s - loss: 0.6543 - accuracy: 0.7421

184/303 [=================>............] - ETA: 0s - loss: 0.6391 - accuracy: 0.7500

210/303 [===================>..........] - ETA: 0s - loss: 0.6251 - accuracy: 0.7476

235/303 [======================>.......] - ETA: 0s - loss: 0.6024 - accuracy: 0.7617

261/303 [========================>.....] - ETA: 0s - loss: 0.6038 - accuracy: 0.7586

286/303 [===========================>..] - ETA: 0s - loss: 0.5924 - accuracy: 0.7587

303/303 [==============================] - 1s 2ms/step - loss: 0.5856 - accuracy: 0.7591


Epoch 6/15
  1/303 [..............................] - ETA: 0s - loss: 1.7859 - accuracy: 0.0000e+00

 28/303 [=>............................] - ETA: 0s - loss: 0.7139 - accuracy: 0.7500    

 54/303 [====>.........................] - ETA: 0s - loss: 0.6085 - accuracy: 0.7963

 80/303 [======>.......................] - ETA: 0s - loss: 0.6189 - accuracy: 0.7750

105/303 [=========>....................] - ETA: 0s - loss: 0.5844 - accuracy: 0.7619

132/303 [============>.................] - ETA: 0s - loss: 0.5959 - accuracy: 0.7652

158/303 [==============>...............] - ETA: 0s - loss: 0.6053 - accuracy: 0.7595

184/303 [=================>............] - ETA: 0s - loss: 0.5918 - accuracy: 0.7609

210/303 [===================>..........] - ETA: 0s - loss: 0.5866 - accuracy: 0.7667

235/303 [======================>.......] - ETA: 0s - loss: 0.5825 - accuracy: 0.7660

261/303 [========================>.....] - ETA: 0s - loss: 0.5567 - accuracy: 0.7778

287/303 [===========================>..] - ETA: 0s - loss: 0.5472 - accuracy: 0.7735

303/303 [==============================] - 1s 2ms/step - loss: 0.5496 - accuracy: 0.7723


Epoch 7/15
  1/303 [..............................] - ETA: 0s - loss: 0.0568 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.6052 - accuracy: 0.8571

 54/303 [====>.........................] - ETA: 0s - loss: 0.5379 - accuracy: 0.7963

 80/303 [======>.......................] - ETA: 0s - loss: 0.5931 - accuracy: 0.7625

106/303 [=========>....................] - ETA: 0s - loss: 0.5669 - accuracy: 0.7642

133/303 [============>.................] - ETA: 0s - loss: 0.6170 - accuracy: 0.7594

159/303 [==============>...............] - ETA: 0s - loss: 0.6714 - accuracy: 0.7547

186/303 [=================>............] - ETA: 0s - loss: 0.6775 - accuracy: 0.7473

211/303 [===================>..........] - ETA: 0s - loss: 0.6401 - accuracy: 0.7583

237/303 [======================>.......] - ETA: 0s - loss: 0.6023 - accuracy: 0.7679

263/303 [=========================>....] - ETA: 0s - loss: 0.6203 - accuracy: 0.7490

288/303 [===========================>..] - ETA: 0s - loss: 0.7169 - accuracy: 0.7396

303/303 [==============================] - 1s 2ms/step - loss: 0.7267 - accuracy: 0.7327


Epoch 8/15
  1/303 [..............................] - ETA: 0s - loss: 0.0039 - accuracy: 1.0000

 26/303 [=>............................] - ETA: 0s - loss: 0.8573 - accuracy: 0.6154

 51/303 [====>.........................] - ETA: 0s - loss: 0.5988 - accuracy: 0.7255

 78/303 [======>.......................] - ETA: 0s - loss: 0.5243 - accuracy: 0.7564

105/303 [=========>....................] - ETA: 0s - loss: 0.5207 - accuracy: 0.7714

131/303 [===========>..................] - ETA: 0s - loss: 0.5343 - accuracy: 0.7557

158/303 [==============>...............] - ETA: 0s - loss: 0.5119 - accuracy: 0.7722

184/303 [=================>............] - ETA: 0s - loss: 0.5040 - accuracy: 0.7826

210/303 [===================>..........] - ETA: 0s - loss: 0.5093 - accuracy: 0.7857

235/303 [======================>.......] - ETA: 0s - loss: 0.5330 - accuracy: 0.7660

261/303 [========================>.....] - ETA: 0s - loss: 0.5285 - accuracy: 0.7739

287/303 [===========================>..] - ETA: 0s - loss: 0.5275 - accuracy: 0.7840

303/303 [==============================] - 1s 2ms/step - loss: 0.5309 - accuracy: 0.7789


Epoch 9/15
  1/303 [..............................] - ETA: 0s - loss: 1.2754 - accuracy: 0.0000e+00

 28/303 [=>............................] - ETA: 0s - loss: 0.5736 - accuracy: 0.7857    

 53/303 [====>.........................] - ETA: 0s - loss: 0.6597 - accuracy: 0.7547

 80/303 [======>.......................] - ETA: 0s - loss: 0.8093 - accuracy: 0.7000

106/303 [=========>....................] - ETA: 0s - loss: 0.7525 - accuracy: 0.7170

132/303 [============>.................] - ETA: 0s - loss: 0.7121 - accuracy: 0.7197

158/303 [==============>...............] - ETA: 0s - loss: 0.7439 - accuracy: 0.7089

185/303 [=================>............] - ETA: 0s - loss: 0.6710 - accuracy: 0.7297

211/303 [===================>..........] - ETA: 0s - loss: 0.6328 - accuracy: 0.7393

236/303 [======================>.......] - ETA: 0s - loss: 0.6445 - accuracy: 0.7415

262/303 [========================>.....] - ETA: 0s - loss: 0.6412 - accuracy: 0.7405

288/303 [===========================>..] - ETA: 0s - loss: 0.6238 - accuracy: 0.7465

303/303 [==============================] - 1s 2ms/step - loss: 0.6029 - accuracy: 0.7558


Epoch 10/15
  1/303 [..............................] - ETA: 0s - loss: 0.0015 - accuracy: 1.0000

 28/303 [=>............................] - ETA: 0s - loss: 0.2826 - accuracy: 0.8214

 55/303 [====>.........................] - ETA: 0s - loss: 0.4082 - accuracy: 0.8000

 82/303 [=======>......................] - ETA: 0s - loss: 0.4264 - accuracy: 0.7927

108/303 [=========>....................] - ETA: 0s - loss: 0.4302 - accuracy: 0.7870

135/303 [============>.................] - ETA: 0s - loss: 0.4513 - accuracy: 0.7852

162/303 [===============>..............] - ETA: 0s - loss: 0.4431 - accuracy: 0.7901

187/303 [=================>............] - ETA: 0s - loss: 0.4867 - accuracy: 0.7807

213/303 [====================>.........] - ETA: 0s - loss: 0.4634 - accuracy: 0.7934

238/303 [======================>.......] - ETA: 0s - loss: 0.4853 - accuracy: 0.7857

264/303 [=========================>....] - ETA: 0s - loss: 0.5123 - accuracy: 0.7614

290/303 [===========================>..] - ETA: 0s - loss: 0.5078 - accuracy: 0.7586

303/303 [==============================] - 1s 2ms/step - loss: 0.5191 - accuracy: 0.7525


Epoch 11/15
  1/303 [..............................] - ETA: 0s - loss: 0.2611 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 0.2631 - accuracy: 0.8519

 52/303 [====>.........................] - ETA: 0s - loss: 0.4387 - accuracy: 0.8269

 76/303 [======>.......................] - ETA: 0s - loss: 0.3876 - accuracy: 0.8553

101/303 [=========>....................] - ETA: 0s - loss: 0.4768 - accuracy: 0.8119

126/303 [===========>..................] - ETA: 0s - loss: 0.4206 - accuracy: 0.8333

152/303 [==============>...............] - ETA: 0s - loss: 0.4314 - accuracy: 0.8289

178/303 [================>.............] - ETA: 0s - loss: 0.4427 - accuracy: 0.8202

204/303 [===================>..........] - ETA: 0s - loss: 0.4864 - accuracy: 0.8039

229/303 [=====================>........] - ETA: 0s - loss: 0.5092 - accuracy: 0.8079

254/303 [========================>.....] - ETA: 0s - loss: 0.5081 - accuracy: 0.8031

280/303 [==========================>...] - ETA: 0s - loss: 0.5310 - accuracy: 0.7893

303/303 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7855


Epoch 12/15
  1/303 [..............................] - ETA: 0s - loss: 0.0207 - accuracy: 1.0000

 27/303 [=>............................] - ETA: 0s - loss: 0.4487 - accuracy: 0.7407

 53/303 [====>.........................] - ETA: 0s - loss: 0.4813 - accuracy: 0.6981

 79/303 [======>.......................] - ETA: 0s - loss: 0.5677 - accuracy: 0.6962

104/303 [=========>....................] - ETA: 0s - loss: 0.5541 - accuracy: 0.7115

130/303 [===========>..................] - ETA: 0s - loss: 0.5154 - accuracy: 0.7385

155/303 [==============>...............] - ETA: 0s - loss: 0.5211 - accuracy: 0.7677

182/303 [=================>............] - ETA: 0s - loss: 0.5940 - accuracy: 0.7363

207/303 [===================>..........] - ETA: 0s - loss: 0.6042 - accuracy: 0.7343

233/303 [======================>.......] - ETA: 0s - loss: 0.6066 - accuracy: 0.7425

259/303 [========================>.....] - ETA: 0s - loss: 0.5759 - accuracy: 0.7375

286/303 [===========================>..] - ETA: 0s - loss: 0.5665 - accuracy: 0.7483

303/303 [==============================] - 1s 2ms/step - loss: 0.5585 - accuracy: 0.7525


Epoch 13/15
  1/303 [..............................] - ETA: 0s - loss: 0.3052 - accuracy: 1.0000

 26/303 [=>............................] - ETA: 0s - loss: 0.4587 - accuracy: 0.8462

 51/303 [====>.........................] - ETA: 0s - loss: 0.4182 - accuracy: 0.8431

 76/303 [======>.......................] - ETA: 0s - loss: 0.4191 - accuracy: 0.7895

101/303 [=========>....................] - ETA: 0s - loss: 0.5347 - accuracy: 0.7327

125/303 [===========>..................] - ETA: 0s - loss: 0.5056 - accuracy: 0.7440

148/303 [=============>................] - ETA: 0s - loss: 0.4592 - accuracy: 0.7838

172/303 [================>.............] - ETA: 0s - loss: 0.4464 - accuracy: 0.8023

196/303 [==================>...........] - ETA: 0s - loss: 0.4483 - accuracy: 0.8061

221/303 [====================>.........] - ETA: 0s - loss: 0.5192 - accuracy: 0.7919

246/303 [=======================>......] - ETA: 0s - loss: 0.5296 - accuracy: 0.7805

271/303 [=========================>....] - ETA: 0s - loss: 0.5313 - accuracy: 0.7823

296/303 [============================>.] - ETA: 0s - loss: 0.5264 - accuracy: 0.7838

303/303 [==============================] - 1s 2ms/step - loss: 0.5182 - accuracy: 0.7855


Epoch 14/15
  1/303 [..............................] - ETA: 0s - loss: 1.6928 - accuracy: 0.0000e+00

 27/303 [=>............................] - ETA: 0s - loss: 0.5899 - accuracy: 0.6296    

 53/303 [====>.........................] - ETA: 0s - loss: 0.4104 - accuracy: 0.7358

 78/303 [======>.......................] - ETA: 0s - loss: 0.5375 - accuracy: 0.7179

102/303 [=========>....................] - ETA: 0s - loss: 0.5251 - accuracy: 0.7353

127/303 [===========>..................] - ETA: 0s - loss: 0.5245 - accuracy: 0.7480

153/303 [==============>...............] - ETA: 0s - loss: 0.5014 - accuracy: 0.7647

179/303 [================>.............] - ETA: 0s - loss: 0.4787 - accuracy: 0.7765

204/303 [===================>..........] - ETA: 0s - loss: 0.5225 - accuracy: 0.7745

230/303 [=====================>........] - ETA: 0s - loss: 0.4963 - accuracy: 0.7870

255/303 [========================>.....] - ETA: 0s - loss: 0.5117 - accuracy: 0.7804

281/303 [==========================>...] - ETA: 0s - loss: 0.5398 - accuracy: 0.7758

303/303 [==============================] - 1s 2ms/step - loss: 0.5443 - accuracy: 0.7723


Epoch 15/15
  1/303 [..............................] - ETA: 0s - loss: 0.0128 - accuracy: 1.0000

 26/303 [=>............................] - ETA: 0s - loss: 0.5881 - accuracy: 0.8462

 52/303 [====>.........................] - ETA: 0s - loss: 0.5549 - accuracy: 0.8077

 77/303 [======>.......................] - ETA: 0s - loss: 0.5368 - accuracy: 0.8052

102/303 [=========>....................] - ETA: 0s - loss: 0.5866 - accuracy: 0.7647

127/303 [===========>..................] - ETA: 0s - loss: 0.5418 - accuracy: 0.7874

153/303 [==============>...............] - ETA: 0s - loss: 0.4920 - accuracy: 0.8039

179/303 [================>.............] - ETA: 0s - loss: 0.5355 - accuracy: 0.7877

203/303 [===================>..........] - ETA: 0s - loss: 0.5127 - accuracy: 0.7931

228/303 [=====================>........] - ETA: 0s - loss: 0.5288 - accuracy: 0.7807

253/303 [========================>.....] - ETA: 0s - loss: 0.5183 - accuracy: 0.7866

279/303 [==========================>...] - ETA: 0s - loss: 0.5194 - accuracy: 0.7921

303/303 [==============================] - 1s 2ms/step - loss: 0.5150 - accuracy: 0.7855


## Alternative to feature columns

Passing a dictionary as an input to a model is as easy as creating a matching dictionary of `tf.keras.layers.Input` layers, applying any pre-processing and stacking them up using the [functional api](../../guide/keras/functional.ipynb). You can use this as an alternative to [feature columns](../keras/feature_columns.ipynb).

In [16]:
inputs = {key: tf.keras.layers.Input(shape=(), name=key) for key in df.keys()}
x = tf.stack(list(inputs.values()), axis=-1)

x = tf.keras.layers.Dense(10, activation='relu')(x)
output = tf.keras.layers.Dense(1)(x)

model_func = tf.keras.Model(inputs=inputs, outputs=output)

model_func.compile(optimizer='adam',
                   loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
                   metrics=['accuracy'])

The easiest way to preserve the column structure of a `pd.DataFrame` when used with `tf.data` is to convert the `pd.DataFrame` to a `dict`, and slice that dictionary.

In [17]:
dict_slices = tf.data.Dataset.from_tensor_slices((df.to_dict('list'), target.values)).batch(16)

In [18]:
for dict_slice in dict_slices.take(1):
  print (dict_slice)

({'age': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([63, 67, 67, 37, 41, 56, 62, 57, 63, 53, 57, 56, 56, 44, 52, 57],
      dtype=int32)>, 'sex': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1], dtype=int32)>, 'cp': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 4, 4, 3, 2, 2, 4, 4, 4, 4, 4, 2, 3, 2, 3, 3], dtype=int32)>, 'trestbps': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([145, 160, 120, 130, 130, 120, 140, 120, 130, 140, 140, 140, 130,
       120, 172, 150], dtype=int32)>, 'chol': <tf.Tensor: shape=(16,), dtype=int32, numpy=
array([233, 286, 229, 250, 204, 236, 268, 354, 254, 203, 192, 294, 256,
       263, 199, 168], dtype=int32)>, 'fbs': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int32)>, 'restecg': <tf.Tensor: shape=(16,), dtype=int32, numpy=array([2, 2, 2, 0, 2, 0, 2, 0, 2, 2, 0, 2, 2, 0, 0, 0], dtype=int32)>, 'thalach': <tf.Tensor: shape=(16

In [19]:
model_func.fit(dict_slices, epochs=15)

Epoch 1/15


 1/19 [>.............................] - ETA: 0s - loss: 112.1279 - accuracy: 0.2500

19/19 [==============================] - ETA: 0s - loss: 98.0478 - accuracy: 0.2739 

19/19 [==============================] - 0s 3ms/step - loss: 98.0478 - accuracy: 0.2739


Epoch 2/15
 1/19 [>.............................] - ETA: 0s - loss: 93.9561 - accuracy: 0.2500

18/19 [===========================>..] - ETA: 0s - loss: 83.1231 - accuracy: 0.2604

19/19 [==============================] - 0s 3ms/step - loss: 81.2776 - accuracy: 0.2739


Epoch 3/15
 1/19 [>.............................] - ETA: 0s - loss: 77.0952 - accuracy: 0.2500

19/19 [==============================] - ETA: 0s - loss: 65.6498 - accuracy: 0.2739

19/19 [==============================] - 0s 3ms/step - loss: 65.6498 - accuracy: 0.2739


Epoch 4/15
 1/19 [>.............................] - ETA: 0s - loss: 61.4107 - accuracy: 0.2500

19/19 [==============================] - ETA: 0s - loss: 51.1218 - accuracy: 0.2739

19/19 [==============================] - 0s 3ms/step - loss: 51.1218 - accuracy: 0.2739


Epoch 5/15
 1/19 [>.............................] - ETA: 0s - loss: 46.8345 - accuracy: 0.2500

19/19 [==============================] - 0s 3ms/step - loss: 37.5949 - accuracy: 0.2739


Epoch 6/15
 1/19 [>.............................] - ETA: 0s - loss: 33.2279 - accuracy: 0.2500

19/19 [==============================] - ETA: 0s - loss: 24.9959 - accuracy: 0.2739

19/19 [==============================] - 0s 3ms/step - loss: 24.9959 - accuracy: 0.2739


Epoch 7/15
 1/19 [>.............................] - ETA: 0s - loss: 20.5548 - accuracy: 0.2500

19/19 [==============================] - ETA: 0s - loss: 13.8553 - accuracy: 0.2739

19/19 [==============================] - 0s 3ms/step - loss: 13.8553 - accuracy: 0.2739


Epoch 8/15
 1/19 [>.............................] - ETA: 0s - loss: 10.3349 - accuracy: 0.2500

19/19 [==============================] - ETA: 0s - loss: 6.0397 - accuracy: 0.2739 

19/19 [==============================] - 0s 3ms/step - loss: 6.0397 - accuracy: 0.2739


Epoch 9/15
 1/19 [>.............................] - ETA: 0s - loss: 3.8027 - accuracy: 0.2500

19/19 [==============================] - ETA: 0s - loss: 1.9379 - accuracy: 0.4455

19/19 [==============================] - 0s 3ms/step - loss: 1.9379 - accuracy: 0.4455


Epoch 10/15
 1/19 [>.............................] - ETA: 0s - loss: 1.5186 - accuracy: 0.5625

19/19 [==============================] - 0s 3ms/step - loss: 1.0329 - accuracy: 0.6337


Epoch 11/15
 1/19 [>.............................] - ETA: 0s - loss: 1.1543 - accuracy: 0.6875

19/19 [==============================] - ETA: 0s - loss: 0.8738 - accuracy: 0.6601

19/19 [==============================] - 0s 3ms/step - loss: 0.8738 - accuracy: 0.6601


Epoch 12/15
 1/19 [>.............................] - ETA: 0s - loss: 1.0486 - accuracy: 0.6875

19/19 [==============================] - ETA: 0s - loss: 0.8148 - accuracy: 0.6865

19/19 [==============================] - 0s 3ms/step - loss: 0.8148 - accuracy: 0.6865


Epoch 13/15
 1/19 [>.............................] - ETA: 0s - loss: 0.9772 - accuracy: 0.6875

19/19 [==============================] - 0s 3ms/step - loss: 0.7816 - accuracy: 0.6898


Epoch 14/15
 1/19 [>.............................] - ETA: 0s - loss: 0.9238 - accuracy: 0.6875

19/19 [==============================] - 0s 3ms/step - loss: 0.7593 - accuracy: 0.6898


Epoch 15/15
 1/19 [>.............................] - ETA: 0s - loss: 0.8819 - accuracy: 0.6875

19/19 [==============================] - 0s 3ms/step - loss: 0.7429 - accuracy: 0.6997
